/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List assignable organizations
         * @description Returns every organization a member may be assigned to. This release produces only the default "Naja Echo" organization and offers no way to create, rename, or delete one (FR-015), so the list is expected to contain exactly one entry.
         */
        get: operations["getAdminOrganizations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set or clear a member's current organization
         * @description Sets the member's current organization, or clears it when `organizationId` is null (FR-012). Idempotent: assigning a member to the organization they are already in leaves state unchanged.
         *     Any previously current membership is cleared in the same transaction, so a member never holds two current memberships (FR-004). Records the member already owns stay with the organization they were created in and are not transferred (FR-016); the presence of such records never blocks the change (FR-017).
         *     Takes effect on the member's next request without a sign-out (FR-014). Emits a structured log event identifying the acting admin, the affected member, and both organizations (FR-018).
         *     Error `type` values: `urn:najaecho:error:user-not-found`, `urn:najaecho:error:organization-not-found`.
         */
        put: operations["assignOrganizationForUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List members with their roles, characters, and organization
         * @description Existing endpoint (spec 017), extended by this feature. Each member now carries an `organization` field holding their current organization, or null when they have no current membership (FR-011).
         *     This listing is not itself organization-scoped — an admin sees every registered member regardless of organization, because member administration is not organization-scoped data (FR-025).
         */
        get: operations["getAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace a member's roles
         * @description Pre-existing endpoint, documented here to close a contract gap — it shipped without any contract entry. Replaces the member's role set entirely; roles absent from the request are removed.
         *     Error `type` value: `urn:najaecho:error:user-not-found`. An unknown role name returns 400 with the offending role in the detail.
         */
        put: operations["assignRolesForUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OrganizationSummary: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        OrganizationListResponse: {
            organizations: components["schemas"]["OrganizationSummary"][];
        };
        AssignOrganizationRequest: {
            /**
             * Format: uuid
             * @description The organization to make current for this member. Null clears the member's current organization, leaving them with no current membership — a valid state (FR-005).
             */
            organizationId: string | null;
        };
        AssignRolesRequest: {
            /** @description The complete set of roles the member should hold after this call. */
            roles: ("Admin" | "Quartermaster" | "CrewResourceOfficer")[];
        };
        AdminUserCharacterResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            handle: string;
        };
        AdminUserResponse: {
            /** Format: uuid */
            id: string;
            authName: string;
            roles: string[];
            characters: components["schemas"]["AdminUserCharacterResponse"][];
            /** @description The member's current organization, or null when they hold no current membership. */
            organization: components["schemas"]["OrganizationSummary"] | null;
        };
        AdminUserListResponse: {
            users: components["schemas"]["AdminUserResponse"][];
        };
        ProblemDetails: {
            type?: string;
            title?: string;
            /** Format: int32 */
            status?: number;
            detail?: string;
        };
    };
    responses: {
        /** @description The request is not authenticated. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The caller is authenticated but is not a global admin. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description The member's identifier. */
        UserId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAdminOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The organizations available for assignment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    assignOrganizationForUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The member's identifier. */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignOrganizationRequest"];
            };
        };
        responses: {
            /** @description The assignment was saved. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request body was malformed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The member does not exist (`urn:najaecho:error:user-not-found`), or the requested organization does not exist (`urn:najaecho:error:organization-not-found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getAdminUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All registered members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    assignRolesForUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The member's identifier. */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRolesRequest"];
            };
        };
        responses: {
            /** @description The roles were saved. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description One or more role names are not recognised. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The member does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
