// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NajaEcho.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NajaEcho.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730173657_AddBlueprintComponentAttributes")]
    partial class AddBlueprintComponentAttributes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", "public");
                });

            modelBuilder.Entity("NajaEcho.Domain.Blueprints.CraftingBlueprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("CigDataError")
                        .HasColumnType("boolean")
                        .HasColumnName("cig_data_error");

                    b.Property<string>("ComponentClass")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("component_class");

                    b.Property<string>("ComponentGrade")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("component_grade");

                    b.Property<short?>("ComponentSize")
                        .HasColumnType("smallint")
                        .HasColumnName("component_size");

                    b.Property<string>("Gear")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("gear");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("manufacturer");

                    b.Property<Guid>("ProductEntityClass")
                        .HasColumnType("uuid")
                        .HasColumnName("product_entity_class");

                    b.Property<string>("ProductName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("product_name");

                    b.Property<string>("Subtype")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subtype");

                    b.Property<string>("SuggestedName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("suggested_name");

                    b.Property<Guid?>("SuggestedProductEntityClass")
                        .HasColumnType("uuid")
                        .HasColumnName("suggested_product_entity_class");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("tag");

                    b.Property<JsonDocument>("Tiers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tiers");

                    b.Property<string>("Type")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_blueprints");

                    b.HasIndex("ProductName")
                        .HasDatabaseName("ix_blueprints_product_name");

                    b.ToTable("blueprints", "sc");
                });

            modelBuilder.Entity("NajaEcho.Domain.Blueprints.CraftingBlueprintSlotOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<int?>("MatchedUexId")
                        .HasColumnType("integer")
                        .HasColumnName("matched_uex_id");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("material_name");

                    b.Property<int>("MinQuality")
                        .HasColumnType("integer")
                        .HasColumnName("min_quality");

                    b.Property<int>("OptionIndex")
                        .HasColumnType("integer")
                        .HasColumnName("option_index");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer")
                        .HasColumnName("slot_index");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("slot_name");

                    b.Property<Guid>("TierId")
                        .HasColumnType("uuid")
                        .HasColumnName("tier_id");

                    b.HasKey("Id")
                        .HasName("pk_blueprint_slot_options");

                    b.HasIndex("MatchedUexId")
                        .HasDatabaseName("ix_blueprint_slot_options_matched_uex_id");

                    b.HasIndex("MaterialName")
                        .HasDatabaseName("ix_blueprint_slot_options_material_name");

                    b.HasIndex("TierId")
                        .HasDatabaseName("ix_blueprint_slot_options_tier_id");

                    b.HasIndex("TierId", "SlotIndex", "OptionIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_blueprint_slot_options_tier_slot_option");

                    b.ToTable("blueprint_slot_options", "sc");
                });

            modelBuilder.Entity("NajaEcho.Domain.Blueprints.CraftingBlueprintTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BlueprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("blueprint_id");

                    b.Property<int>("CraftTimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("craft_time_seconds");

                    b.Property<int>("TierIndex")
                        .HasColumnType("integer")
                        .HasColumnName("tier_index");

                    b.HasKey("Id")
                        .HasName("pk_blueprint_tiers");

                    b.HasIndex("BlueprintId")
                        .HasDatabaseName("ix_blueprint_tiers_blueprint_id_tier0")
                        .HasFilter("tier_index = 0");

                    b.HasIndex("BlueprintId", "TierIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_blueprint_tiers_blueprint_id_tier_index");

                    b.ToTable("blueprint_tiers", "sc");
                });

            modelBuilder.Entity("NajaEcho.Domain.Blueprints.CraftingDataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("BlacklistedEntityClasses")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("blacklisted_entity_classes");

                    b.Property<JsonDocument>("BlacklistedResources")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("blacklisted_resources");

                    b.Property<int>("DismantleTimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("dismantle_time_seconds");

                    b.Property<double>("Efficiency")
                        .HasColumnType("double precision")
                        .HasColumnName("efficiency");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<int>("TotalBlueprints")
                        .HasColumnType("integer")
                        .HasColumnName("total_blueprints");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer")
                        .HasColumnName("total_items");

                    b.Property<int>("TotalProducts")
                        .HasColumnType("integer")
                        .HasColumnName("total_products");

                    b.Property<int>("TotalResources")
                        .HasColumnType("integer")
                        .HasColumnName("total_resources");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_crafting_datasets");

                    b.ToTable("crafting_datasets", "sc");
                });

            modelBuilder.Entity("NajaEcho.Domain.Blueprints.CraftingMaterial", b =>
                {
                    b.Property<string>("Kind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<int?>("MatchedUexId")
                        .HasColumnType("integer")
                        .HasColumnName("matched_uex_id");

                    b.HasKey("Kind", "Name")
                        .HasName("pk_crafting_materials");

                    b.HasIndex("MatchedUexId")
                        .HasDatabaseName("ix_crafting_materials_matched_uex_id");

                    b.ToTable("crafting_materials", "sc");
                });

            modelBuilder.Entity("NajaEcho.Domain.Blueprints.CraftingProperty", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("property_key");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("NameOverrides")
                        .HasColumnType("jsonb")
                        .HasColumnName("name_overrides");

                    b.Property<string>("Unit")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("unit");

                    b.HasKey("Key")
                        .HasName("pk_crafting_properties");

                    b.ToTable("crafting_properties", "sc");
                });

            modelBuilder.Entity("NajaEcho.Domain.Blueprints.UserBlueprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("BlueprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("blueprint_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_blueprints");

                    b.HasIndex("BlueprintId")
                        .HasDatabaseName("ix_user_blueprints_blueprint_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_blueprints_user_id");

                    b.HasIndex("UserId", "BlueprintId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_blueprints_user_blueprint");

                    b.ToTable("user_blueprints", "public");
                });

            modelBuilder.Entity("NajaEcho.Domain.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("handle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("Handle")
                        .IsUnique()
                        .HasDatabaseName("ux_characters_handle_lower");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_characters_owner_user_id");

                    b.ToTable("characters", "public");
                });

            modelBuilder.Entity("NajaEcho.Domain.Characters.PendingCharacterRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_pending_character_registrations");

                    b.HasIndex("OwnerUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_pending_character_registrations_owner_user_id");

                    b.ToTable("pending_character_registrations", "public");
                });

            modelBuilder.Entity("NajaEcho.Domain.Commodities.Commodity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<int?>("IdItem")
                        .HasColumnType("integer")
                        .HasColumnName("id_item");

                    b.Property<int?>("IdParent")
                        .HasColumnType("integer")
                        .HasColumnName("id_parent");

                    b.PrimitiveCollection<int[]>("IdsMoons")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("ids_moons");

                    b.Property<string>("IdsMoonsRaw")
                        .HasColumnType("text")
                        .HasColumnName("ids_moons_raw");

                    b.PrimitiveCollection<int[]>("IdsOrbits")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("ids_orbits");

                    b.Property<string>("IdsOrbitsRaw")
                        .HasColumnType("text")
                        .HasColumnName("ids_orbits_raw");

                    b.PrimitiveCollection<int[]>("IdsPlanets")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("ids_planets");

                    b.Property<string>("IdsPlanetsRaw")
                        .HasColumnType("text")
                        .HasColumnName("ids_planets_raw");

                    b.PrimitiveCollection<int[]>("IdsPoi")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("ids_poi");

                    b.Property<string>("IdsPoiRaw")
                        .HasColumnType("text")
                        .HasColumnName("ids_poi_raw");

                    b.PrimitiveCollection<int[]>("IdsStarSystems")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("ids_star_systems");

                    b.Property<string>("IdsStarSystemsRaw")
                        .HasColumnType("text")
                        .HasColumnName("ids_star_systems_raw");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsAvailableLive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available_live");

                    b.Property<bool>("IsBuggy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_buggy");

                    b.Property<bool>("IsBuyable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_buyable");

                    b.Property<bool>("IsExplosive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_explosive");

                    b.Property<bool>("IsExtractable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_extractable");

                    b.Property<bool>("IsFuel")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fuel");

                    b.Property<bool>("IsHarvestable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_harvestable");

                    b.Property<bool>("IsIllegal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_illegal");

                    b.Property<bool>("IsInert")
                        .HasColumnType("boolean")
                        .HasColumnName("is_inert");

                    b.Property<bool>("IsMineral")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mineral");

                    b.Property<bool>("IsPure")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pure");

                    b.Property<bool>("IsRaw")
                        .HasColumnType("boolean")
                        .HasColumnName("is_raw");

                    b.Property<bool>("IsRefinable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_refinable");

                    b.Property<bool>("IsRefined")
                        .HasColumnType("boolean")
                        .HasColumnName("is_refined");

                    b.Property<bool>("IsSellable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sellable");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_temporary");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<bool>("IsVolatileQt")
                        .HasColumnType("boolean")
                        .HasColumnName("is_volatile_qt");

                    b.Property<bool>("IsVolatileTime")
                        .HasColumnType("boolean")
                        .HasColumnName("is_volatile_time");

                    b.Property<string>("Kind")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("RawData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<string>("Slug")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("SoftDeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("soft_deleted_at");

                    b.Property<long?>("SourceDateAdded")
                        .HasColumnType("bigint")
                        .HasColumnName("source_date_added");

                    b.Property<DateTimeOffset?>("SourceDateAddedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_date_added_utc");

                    b.Property<long?>("SourceDateModified")
                        .HasColumnType("bigint")
                        .HasColumnName("source_date_modified");

                    b.Property<DateTimeOffset?>("SourceDateModifiedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_date_modified_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UexId")
                        .HasColumnType("integer")
                        .HasColumnName("uex_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("uuid");

                    b.Property<double?>("WeightScu")
                        .HasColumnType("double precision")
                        .HasColumnName("weight_scu");

                    b.Property<string>("Wiki")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("wiki");

                    b.HasKey("Id")
                        .HasName("pk_commodities");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_commodities_status");

                    b.HasIndex("UexId")
                        .IsUnique()
                        .HasDatabaseName("ix_commodities_uex_id");

                    b.ToTable("commodities", "sc");
                });

            modelBuilder.Entity("NajaEcho.Domain.Hangar.HangarEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uuid")
                        .HasColumnName("ship_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_hangar_entries");

                    b.HasIndex("ShipId")
                        .HasDatabaseName("ix_hangar_entries_ship_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_hangar_entries_user_id");

                    b.HasIndex("UserId", "ShipId")
                        .IsUnique()
                        .HasDatabaseName("ux_hangar_entries_user_ship");

                    b.ToTable("hangar_entries", "public");
                });

            modelBuilder.Entity("NajaEcho.Domain.ItemCategories.ItemCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<bool>("IsGameRelated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_game_related");

                    b.Property<bool>("IsMining")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mining");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("RawData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<string>("Section")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("section");

                    b.Property<DateTimeOffset?>("SourceDateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_date_added");

                    b.Property<DateTimeOffset?>("SourceDateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_date_modified");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.Property<int>("UexId")
                        .HasColumnType("integer")
                        .HasColumnName("uex_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_item_categories");

                    b.HasIndex("Section")
                        .HasDatabaseName("ix_item_categories_section");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_item_categories_type");

                    b.HasIndex("UexId")
                        .IsUnique()
                        .HasDatabaseName("ix_item_categories_uex_id");

                    b.ToTable("item_categories", "sc");
                });

            modelBuilder.Entity("NajaEcho.Domain.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("category");

                    b.Property<string>("Color")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("color");

                    b.Property<string>("Color2")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("color2");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("company_name");

                    b.Property<string>("GameVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_version");

                    b.Property<int>("IdCategory")
                        .HasColumnType("integer")
                        .HasColumnName("id_category");

                    b.Property<int?>("IdCompany")
                        .HasColumnType("integer")
                        .HasColumnName("id_company");

                    b.Property<int?>("IdParent")
                        .HasColumnType("integer")
                        .HasColumnName("id_parent");

                    b.Property<int?>("IdVehicle")
                        .HasColumnType("integer")
                        .HasColumnName("id_vehicle");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<bool>("IsCommodity")
                        .HasColumnType("boolean")
                        .HasColumnName("is_commodity");

                    b.Property<bool>("IsExclusiveConcierge")
                        .HasColumnType("boolean")
                        .HasColumnName("is_exclusive_concierge");

                    b.Property<bool>("IsExclusivePledge")
                        .HasColumnType("boolean")
                        .HasColumnName("is_exclusive_pledge");

                    b.Property<bool>("IsExclusiveSubscriber")
                        .HasColumnType("boolean")
                        .HasColumnName("is_exclusive_subscriber");

                    b.Property<bool>("IsHarvestable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_harvestable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("Notification")
                        .HasColumnType("text")
                        .HasColumnName("notification");

                    b.Property<string>("Quality")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("quality");

                    b.Property<JsonDocument>("RawData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<string>("Section")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("section");

                    b.Property<string>("Size")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("size");

                    b.Property<string>("Slug")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("SoftDeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("soft_deleted_at");

                    b.Property<DateTimeOffset?>("SourceDateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_date_added");

                    b.Property<DateTimeOffset?>("SourceDateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_date_modified");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UexId")
                        .HasColumnType("integer")
                        .HasColumnName("uex_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UrlStore")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("url_store");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("uuid");

                    b.Property<string>("VehicleName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("vehicle_name");

                    b.Property<string>("Wiki")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("wiki");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("IdCategory")
                        .HasDatabaseName("ix_items_id_category");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_items_status");

                    b.HasIndex("UexId")
                        .HasDatabaseName("ix_items_uex_id");

                    b.HasIndex("Uuid")
                        .HasDatabaseName("ix_items_uuid");

                    b.HasIndex("IdCategory", "UexId")
                        .HasDatabaseName("ix_items_id_category_uex_id");

                    b.ToTable("items", "sc");
                });

            modelBuilder.Entity("NajaEcho.Domain.Locations.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsAvailableLive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available_live");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("RawData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<DateTimeOffset?>("SoftDeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("soft_deleted_at");

                    b.Property<Guid>("StarSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("star_system_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("UexId")
                        .HasColumnType("integer")
                        .HasColumnName("uex_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("StarSystemId")
                        .HasDatabaseName("ix_cities_star_system_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_cities_status");

                    b.HasIndex("UexId")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_uex_id");

                    b.HasIndex("IsAvailable", "IsVisible", "Name")
                        .HasDatabaseName("ix_cities_avail_visible_name");

                    b.ToTable("cities", "sc");
                });

            modelBuilder.Entity("NajaEcho.Domain.Locations.SpaceStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("HasRefinery")
                        .HasColumnType("boolean")
                        .HasColumnName("has_refinery");

                    b.Property<bool>("HasTradeTerminal")
                        .HasColumnType("boolean")
                        .HasColumnName("has_trade_terminal");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsDecommissioned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_decommissioned");

                    b.Property<bool>("IsLandable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_landable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Nickname")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nickname");

                    b.Property<JsonDocument>("RawData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<DateTimeOffset?>("SoftDeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("soft_deleted_at");

                    b.Property<Guid>("StarSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("star_system_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("UexId")
                        .HasColumnType("integer")
                        .HasColumnName("uex_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_space_stations");

                    b.HasIndex("StarSystemId")
                        .HasDatabaseName("ix_space_stations_star_system_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_space_stations_status");

                    b.HasIndex("UexId")
                        .IsUnique()
                        .HasDatabaseName("ix_space_stations_uex_id");

                    b.HasIndex("IsAvailable", "IsDecommissioned", "Name")
                        .HasDatabaseName("ix_space_stations_avail_decomm_name");

                    b.ToTable("space_stations", "sc");
                });

            modelBuilder.Entity("NajaEcho.Domain.Locations.StarSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("RawData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<DateTimeOffset?>("SoftDeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("soft_deleted_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("UexId")
                        .HasColumnType("integer")
                        .HasColumnName("uex_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_star_systems");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_star_systems_status");

                    b.HasIndex("UexId")
                        .IsUnique()
                        .HasDatabaseName("ix_star_systems_uex_id");

                    b.ToTable("star_systems", "sc");
                });

            modelBuilder.Entity("NajaEcho.Domain.Loot.LootLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_loot_ledger");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_loot_ledger_actor_id");

                    b.HasIndex("MemberId", "Kind", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_loot_ledger_member_kind_created");

                    b.ToTable("loot_ledger", "public", t =>
                        {
                            t.HasCheckConstraint("ck_loot_ledger_kind", "kind IN ('OrgPoints', 'LootPoints')");

                            t.HasCheckConstraint("ck_loot_ledger_reason", "length(btrim(reason)) >= 1");
                        });
                });

            modelBuilder.Entity("NajaEcho.Domain.Loot.LootMemberStanding", b =>
                {
                    b.Property<double>("ClaimPriority")
                        .HasColumnType("double precision")
                        .HasColumnName("claim_priority");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("LootPointsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("loot_points_total");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<int>("OrgPointsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("org_points_total");

                    b.ToTable((string)null);

                    b.ToView("loot_member_standing", "public");
                });

            modelBuilder.Entity("NajaEcho.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", "public");
                });

            modelBuilder.Entity("NajaEcho.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_current");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_memberships");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_memberships_organization_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_memberships_user_current")
                        .HasFilter("is_current");

                    b.HasIndex("UserId", "OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_memberships_user_org");

                    b.ToTable("organization_memberships", "public");
                });

            modelBuilder.Entity("NajaEcho.Domain.Ships.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("company_name");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NameFull")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name_full");

                    b.Property<JsonDocument>("RawData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<DateTimeOffset?>("SoftDeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("soft_deleted_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UexId")
                        .HasColumnType("integer")
                        .HasColumnName("uex_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("pk_ships");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ships_status");

                    b.HasIndex("UexId")
                        .IsUnique()
                        .HasDatabaseName("ix_ships_uex_id");

                    b.ToTable("ships", "sc");
                });

            modelBuilder.Entity("NajaEcho.Domain.Warehouse.ItemAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("attribute_name");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<DateTimeOffset?>("SourceDateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_date_added");

                    b.Property<DateTimeOffset?>("SourceDateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_date_modified");

                    b.Property<int?>("UexAttributeId")
                        .HasColumnType("integer")
                        .HasColumnName("uex_attribute_id");

                    b.Property<int>("UexCategoryAttributeId")
                        .HasColumnType("integer")
                        .HasColumnName("uex_category_attribute_id");

                    b.Property<int?>("UexCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("uex_category_id");

                    b.Property<int>("UexItemId")
                        .HasColumnType("integer")
                        .HasColumnName("uex_item_id");

                    b.Property<string>("Unit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("unit");

                    b.Property<string>("Value")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_item_attributes");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_item_attributes_item_id");

                    b.HasIndex("ItemId", "UexCategoryAttributeId")
                        .IsUnique()
                        .HasDatabaseName("ux_item_attributes_item_category_attr");

                    b.ToTable("item_attributes", "sc");
                });

            modelBuilder.Entity("NajaEcho.Domain.Warehouse.ShipComponentAttributes", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<DateTimeOffset>("AttributesFetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attributes_fetched_at");

                    b.Property<string>("Class")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("class");

                    b.Property<string>("Grade")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("grade");

                    b.Property<int?>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.HasKey("ItemId");

                    b.ToTable((string)null);

                    b.ToView("ship_component_attributes", "sc");
                });

            modelBuilder.Entity("NajaEcho.Domain.Warehouse.WarehouseInventoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("LocationType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("location_type");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("Quality")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(500)
                        .HasColumnName("quality");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_warehouse_inventory");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_warehouse_inventory_item_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_warehouse_inventory_location_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_warehouse_inventory_owner_user_id");

                    b.HasIndex("ItemId", "OwnerUserId", "Location")
                        .IsUnique()
                        .HasDatabaseName("ux_warehouse_inventory_item_owner_location");

                    b.ToTable("warehouse_inventory", "public", t =>
                        {
                            t.HasCheckConstraint("ck_warehouse_inventory_location_type", "location_type IN ('Station', 'City')");

                            t.HasCheckConstraint("ck_warehouse_inventory_quality", "quality >= 1 AND quality <= 1000");

                            t.HasCheckConstraint("ck_warehouse_inventory_quantity", "quantity >= 1");
                        });
                });

            modelBuilder.Entity("NajaEcho.Domain.Warehouse.WarehouseMaterialEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("uuid")
                        .HasColumnName("commodity_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("LocationType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("location_type");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("Quality")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(500)
                        .HasColumnName("quality");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_warehouse_material_inventory");

                    b.HasIndex("CommodityId")
                        .HasDatabaseName("ix_warehouse_material_inventory_commodity_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_warehouse_material_inventory_location_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_warehouse_material_inventory_owner_user_id");

                    b.HasIndex("CommodityId", "OwnerUserId", "Location", "Quality")
                        .IsUnique()
                        .HasDatabaseName("ux_warehouse_material_inventory_commodity_owner_location_quality");

                    b.ToTable("warehouse_material_inventory", "public", t =>
                        {
                            t.HasCheckConstraint("ck_warehouse_material_inventory_location_type", "location_type IN ('Station', 'City')");

                            t.HasCheckConstraint("ck_warehouse_material_inventory_quality", "quality >= 1 AND quality <= 1000");

                            t.HasCheckConstraint("ck_warehouse_material_inventory_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("NajaEcho.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("DiscordUsername")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("discord_username");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("NajaEcho.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("NajaEcho.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("NajaEcho.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("NajaEcho.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("NajaEcho.Domain.Blueprints.CraftingBlueprintSlotOption", b =>
                {
                    b.HasOne("NajaEcho.Domain.Blueprints.CraftingBlueprintTier", null)
                        .WithMany()
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blueprint_slot_options_tier_id");
                });

            modelBuilder.Entity("NajaEcho.Domain.Blueprints.CraftingBlueprintTier", b =>
                {
                    b.HasOne("NajaEcho.Domain.Blueprints.CraftingBlueprint", null)
                        .WithMany()
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blueprint_tiers_blueprint_id");
                });

            modelBuilder.Entity("NajaEcho.Domain.Blueprints.UserBlueprint", b =>
                {
                    b.HasOne("NajaEcho.Domain.Blueprints.CraftingBlueprint", null)
                        .WithMany()
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_blueprints_blueprint_id");
                });

            modelBuilder.Entity("NajaEcho.Domain.Characters.Character", b =>
                {
                    b.HasOne("NajaEcho.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_characters_owner_user_id");
                });

            modelBuilder.Entity("NajaEcho.Domain.Characters.PendingCharacterRegistration", b =>
                {
                    b.HasOne("NajaEcho.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pending_character_registrations_owner_user_id");
                });

            modelBuilder.Entity("NajaEcho.Domain.Hangar.HangarEntry", b =>
                {
                    b.HasOne("NajaEcho.Domain.Ships.Ship", null)
                        .WithMany()
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hangar_entries_ship_id");
                });

            modelBuilder.Entity("NajaEcho.Domain.Locations.City", b =>
                {
                    b.HasOne("NajaEcho.Domain.Locations.StarSystem", "StarSystem")
                        .WithMany()
                        .HasForeignKey("StarSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cities_star_systems_star_system_id");

                    b.Navigation("StarSystem");
                });

            modelBuilder.Entity("NajaEcho.Domain.Locations.SpaceStation", b =>
                {
                    b.HasOne("NajaEcho.Domain.Locations.StarSystem", "StarSystem")
                        .WithMany()
                        .HasForeignKey("StarSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_space_stations_star_systems_star_system_id");

                    b.Navigation("StarSystem");
                });

            modelBuilder.Entity("NajaEcho.Domain.Loot.LootLedgerEntry", b =>
                {
                    b.HasOne("NajaEcho.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_loot_ledger_actor_id");

                    b.HasOne("NajaEcho.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loot_ledger_member_id");
                });

            modelBuilder.Entity("NajaEcho.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.HasOne("NajaEcho.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_organization_id");

                    b.HasOne("NajaEcho.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_user_id");
                });

            modelBuilder.Entity("NajaEcho.Domain.Warehouse.ItemAttribute", b =>
                {
                    b.HasOne("NajaEcho.Domain.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_attributes_item_id");
                });

            modelBuilder.Entity("NajaEcho.Domain.Warehouse.WarehouseInventoryEntry", b =>
                {
                    b.HasOne("NajaEcho.Domain.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_warehouse_inventory_item_id");
                });

            modelBuilder.Entity("NajaEcho.Domain.Warehouse.WarehouseMaterialEntry", b =>
                {
                    b.HasOne("NajaEcho.Domain.Commodities.Commodity", null)
                        .WithMany()
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_warehouse_material_inventory_commodity_id");
                });
#pragma warning restore 612, 618
        }
    }
}
